import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
                <script
              async
              src="https://www.googletagmanager.com/gtag/js?id=G-9XS7S8ZZMC"
            ></script>
            <script>
              window.dataLayer = window.dataLayer || []; function gtag(){}
              gtag('js', new Date()); gtag('config', 'G-9XS7S8ZZMC');
            </script>
      </Head>
      <body className={``}>{children}</body>
    </html>
  );
}
